CREATE ROLE authenticator NOINHERIT;
CREATE ROLE kitchen_role;
CREATE ROLE admins;
CREATE ROLE anonymous;
CREATE ROLE backup_user;

-- AUTHENTICATOR FOR LOGIN USER
GRANT anonymous, kitchen_role, admins TO authenticator;

-- ANONYMOUS FOR SIGNUP AND GETTERS USER
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anonymous;

-- ADMIN FOR ALL USES
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admins;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admins;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO admins;

-- KITCHEN ROLE ACCESS TO ALL TABLES EXEPT USERS
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO kitchen_role;
REVOKE SELECT, INSERT, UPDATE, DELETE ON users FROM kitchen_role;

-- ONLY RUN THIS AFTER CREATING TRIGGER FUNCTIONS 
GRANT EXECUTE ON FUNCTION
  login(text, text),
  login_admin(text, text)
  signup(text, text, text)
  TO anonymous;
  
-- BACKUP USER
GRANT SELECT ON ALL TABLES IN SCHEMA public TO backup_user;
